### ISSUE TITLE
Transformer Component

### ISSUE THREAD

**Issue by FelipeCSantos** [typhoon-hil/opendss-typhoon-hil-interface#123]
- Is not identifying old Yg connections. It loads an old model converting Yg to Y connection

- Depending on a sequence of connections changing, the clock of the internal transformer (core) is not changed properly
![image](https://github.com/typhoon-hil/opendss-typhoon-hil-interface/assets/22376644/0773d6d0-8d01-4fc0-b9ff-73067fa8f29f)

- The neutral is not floating on the Y connections
![image](https://github.com/typhoon-hil/opendss-typhoon-hil-interface/assets/22376644/544f4774-9190-4086-adf7-bf5694fe48fe)
![image](https://github.com/typhoon-hil/opendss-typhoon-hil-interface/assets/22376644/662f773b-a441-49df-b599-1ce3e84bae4e)

**Comment by murilones** [comment]
fixed on v0.5
