### ISSUE TITLE
Load Component - Single-Phase Load in PQ mode has disabled blocks

### ISSUE THREAD

**Issue by FelipeCSantos** [typhoon-hil/opendss-typhoon-hil-interface#24]
![image](https://user-images.githubusercontent.com/22376644/209154185-8823b1dc-9869-4b34-ad1d-2486b35f3330.png)

**Comment by FelipeCSantos** [comment]
Maybe it is duplicated with Issue #17

**Comment by murilones** [comment]
It is duplicated. There's a pull request with the fix awaiting approval to close issue #17 .
I'm closing this issue.
