### ISSUE TITLE
Load Component - Include "Vmin" and "Vmax" properties

### ISSUE THREAD

**Issue by FelipeCSantos** [typhoon-hil/opendss-typhoon-hil-interface#26]
Those limits are considered to disable the load model control and change it to constant impedance.

![image](https://user-images.githubusercontent.com/22376644/209216544-6fce5533-50c0-4216-b993-27c10c89dc3a.png)

**Comment by murilones** [comment]
How do you see this being applied on Typhoon's real time simulation? would you have a mix of CIL and CPL dynamic behavior?
